### ISSUE TITLE
how to get the arm version of elasticsearch 6.x.x

### ISSUE THREAD

**Issue by glianyi** [elyalvarado/elasticsearch-docker-arm64#3]
I can not find a elasticsearch 6.x.x on the official site,can you tell me where to get it?
or,you build it yourself?

**Comment by arlando** [comment]
You have to compile from scratch. It's not very hard and it's not very easy. If you get the openjdk 9 arm64  image, clone the elasticsearch repo, checkout 6.x, and run gradlew assemble (or w/e the build command was at that time) it might build.

**Comment by xrl** [comment]
Thanks to Arlando's tips, on my Apple ARM OS X I can use docker for mac to build the release. First clone the elasticsearch git repo, then checkout their `6.8` branch, and from inside the root of the elasticsearch checkout:

```
docker run -v $PWD:/elasticsearch openjdk:11 bash -c "cd /elasticsearch; ./gradew assemble"
```

or similar. It probably helps that I'm running this from an ARM computer.

**Comment by arlando** [comment]
Yes!! Super, that's elegant! You can also reverse engineer their docker
container ;)  https://github.com/elastic/elasticsearch-docker
